# Generated by Django 4.2.17 on 2026-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationstaff',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationstudent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notificationstaff',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
