# Generated by Django 4.2.17 on 2026-08-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_student_date_of_birth_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='applied_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.parent'),
        ),
        migrations.CreateModel(
            name='NotificationParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.parent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
