# Generated by Django 4.2.17 on 2026-08-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_leavereportstudent_applied_by_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'HOD'), ('2', 'Staff'), ('3', 'Student'), ('4', 'Parent')], default='1', max_length=1),
        ),
    ]
