# Generated by Django 4.2.30 on 2026-08-17 10:01, hand-edited: the
# autogenerated RemoveField+AddField pair for Subject.staff would have
# silently dropped every existing subject's teacher assignment (a plain
# FK->M2M conversion carries no data across on its own) - this rewrite
# renames the old FK column out of the way, adds the new M2M field,
# copies every existing assignment across via RunPython, and only then
# drops the renamed-away old column.

from django.db import migrations, models
import django.db.models.deletion


def copy_staff_fk_to_m2m(apps, schema_editor):
    Subject = apps.get_model('main_app', 'Subject')
    for subject in Subject.objects.all():
        if subject.staff_old_id is not None:
            subject.staff.add(subject.staff_old_id)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main_app.staff'),
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='staff',
            new_name='staff_old',
        ),
        migrations.AddField(
            model_name='subject',
            name='staff',
            field=models.ManyToManyField(to='main_app.staff'),
        ),
        migrations.RunPython(copy_staff_fk_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subject',
            name='staff_old',
        ),
    ]
