# Generated by Django 4.2.30 on 2026-08-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_attendance_taken_by_remove_subject_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='school_days',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
