# Generated by Django 4.2.30 on 2026-08-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_session_school_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('email_host', models.CharField(blank=True, max_length=255)),
                ('email_port', models.PositiveIntegerField(blank=True, null=True)),
                ('email_host_user', models.CharField(blank=True, max_length=255)),
                ('email_host_password', models.CharField(blank=True, max_length=255)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
