# Generated by Django 4.2.30 on 2026-09-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_sitesettings_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_secondary_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main_app.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_courses',
            field=models.ManyToManyField(blank=True, related_name='secondary_students', to='main_app.course'),
        ),
    ]
