# Generated by Django 4.2.30 on 2026-10-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_leavereportstaff_decided_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exempt_from_date_restrictions',
            field=models.BooleanField(default=False, help_text='Allow Take Attendance for this class on any date, with no school-day or "most recent day" restriction. Use this for a class that doesn\'t follow the normal school calendar (e.g. an occasional commemoration).'),
        ),
    ]
